// Search constants

export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT/SEARCH' 
export const SEARCH_FETCHING = 'SEARCH_FETCHING/SEARCH' 
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS/SEARCH' 
export const SEARCH_FAILURE = 'SEARCH_FAILURE/SEARCH'

//  Modal constants

export const SET_MODAL_DATA = 'SET_MODAL_DATA/MODAL' 

// Favorites constants

export const ADD_FAVORITES = 'ADD_FAVORITES/FAVORITES'
export const REMOVE_FAVORITES = 'REMOVE_FAVORITES/FAVORITES'

// History constants

export const ADD_HISTORY = 'ADD_HISTORY/HISTORY'
export const REMOVE_HISTORY = 'REMOVE_HISTORY/HISTORY'
export const HISTORY_FETCHING = 'HISTORY_FETCHING/HISTORY' 
export const HISTORY_SUCCESS = 'HISTORY_SUCCESS/HISTORY' 
export const HISTORY_FAILURE = 'HISTORY_FAILURE/HISTORY' 